name: Notification
on:
  push:
    branches:
      - main
    paths:
      - /**/*.md
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}

      - name: Get commit message
        run: |
          echo "Commit_Message=$(git log --pretty=format:%s --all --abbrev-commit)" >> $GITHUB_ENV

      - name: Send message
        uses: appleboy/discord-action@v1.2.0
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          color: "#faed90"
          args: |
            {
              "description": "A new commit has been pushed to **${{ github.repository }}** by **@${{ github.actor }}**.",
              "color": 3447003,
              "fields": [
                {
                  "name": "Commit Message",
                  "value": "${{ env.Commit_Message }}",
                  "inline": false
                },
                {
                  "name": "Link",
                  "value": "[**View Repository**](${{ github.repositoryUrl }})", // ハイパーリンク化
                  "inline": true
                }
              ]
            }

#            "New commit in ${{ github.repository }} by @${{ github.actor }}.
#            Commit: ${{ env.Commit_Message }}
#            URL: ${{ github.repositoryUrl }}"
