name: Upload Wiki
on:
  push:
    paths:
      - ./**/*.md
  workflow_dispatch:

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # Wikiリポジトリをチェックアウト
      - name: Checkout Wiki repository
        uses: actions/checkout@v5
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki
          token: ${{ secrets.WIKI_PAT }}
          fetch-depth: 0 # 履歴を全て取得

      # Wikiリポジトリを更新
      - name: Update Wiki repository
        run: |
          rm -f wiki/*.md
          find . -name "*.md" -not -name "README.md" -not -name "Home.md" -exec cp {} wiki/ \;

      # 差分をコミット
      - name: Stage and count changes
        working-directory: wiki
        id: staging
        run: |
          git add .
          echo "NUM_OF_STAGED=$(git diff --staged --name-only | wc -l)" >> $GITHUB_OUTPUT

      # 変更がある場合のみコミット
      - name: Commit and Push wiki pages
        working-directory: wiki
        if: steps.staging.outputs.NUM_OF_STAGED > 0
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Actions"
          git commit -m "${{ github.workflow }}"
          git push